### ISSUE TITLE
vmi-win-guid command timeout

### ISSUE THREAD

**Issue by LANopop** [CERT-Polska/drakvuf-sandbox#91] opened 2020-05-06 14:10 UTC
**Describe the bug**

During Setup at the point when i run the command ``sudo draksetup postinstall`` i run into a timeout.

```
root@debian:/home/martin# draksetup postinstall
Traceback (most recent call last):
  File "/usr/lib/python3.7/subprocess.py", line 474, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 939, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.7/subprocess.py", line 1682, in _communicate
    self._check_timeout(endtime, orig_timeout)
  File "/usr/lib/python3.7/subprocess.py", line 982, in _check_timeout
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['vmi-win-guid', 'name', 'vm-0']' timed out after 30 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/draksetup", line 7, in <module>
    ds.main()
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/draksetup.py", line 389, in main
    generate_profiles()
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/draksetup.py", line 233, in generate_profiles
    output = subprocess.check_output(['vmi-win-guid', 'name', 'vm-0'], timeout=30).decode('utf-8')
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 479, in run
    stderr=stderr)
subprocess.TimeoutExpired: Command '['vmi-win-guid', 'name', 'vm-0']' timed out after 30 seconds
```

I guessing this is, because the command ``vmi-win-guid name vm-0`` takes around 1 minute to complete.

I am running all of this in a KVM on proxmox.

**How to reproduce**

1. Install drakcore and drakrun
2. Start and install a Windows 10 x64 image
3. Execute sudo draksetup postinstall

**Output of the [status checking commands](https://github.com/CERT-Polska/drakvuf-sandbox#checking-service-status)**
```
root@debian:/home/martin# drak-healthcheck
Checking daemon status...
drak-web.service              OK
drak-system.service           OK
drak-minio.service            OK
drak-postprocess.service      OK

Checking worker status...
drakrun@1.service             ERROR
```

**Comment by BonusPlay** [comment] 2020-05-06 14:47
I'm afraid running on KVM is not supported yet, as drakvuf project itself has some problems with KVM (drakvuf builds are created with `--disable-kvm` flag). We have tested nested virtualization as in `kvm => xen => windows` and haven't managed to get it working (yet).

Hopefully in the future we will support it, but at the moment we don't support running on KVM.

**Comment by icedevml** [comment] 2020-05-06 15:05
@BonusPlay If he already succeeded to install Windows on `vm-0`, then there is a huge chance that his setup will actually work, so it would be good to debug this further.

@LANopop The error you have pasted looks like there is some trouble with LibVMI itself. What guest operating system are you using and what is the name/hash of ISO you are using?

**Comment by icedevml** [comment] 2020-05-06 15:08
@LANopop Ah, you wrote that it is Windows 10 x64. Could you point to the exact version of Win 10 ISO? It would be easier to reproduce this bug.

**Comment by LANopop** [comment] 2020-05-06 16:19
> @LANopop Ah, you wrote that it is Windows 10 x64. Could you point to the exact version of Win 10 ISO? It would be easier to reproduce this bug.

**KVM Information**:
Linux debian 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux
debian 10.3
windows 10 x64 iso md5 hash: 23e397a21a9e01f141c64b7e1260314a (i had this iso stored somewhere and dont remember how i got it)

**Proxmox Information:** 
Kernel Version Linux 5.3.18-3-pve #1 SMP PVE 5.3.18-3
pve-manager/6.1-8/806edfe1
debian 10.3

the installation of windows itself took very long (at least 30 minutes). Also for some reason windows 7 x64 installation always blue screened after the installation was over and it started to boot.

**Comment by icedevml** [comment] 2020-05-06 17:01
> Also for some reason windows 7 x64 installation always blue screened after the installation was over and it started to boot.

For some reason Windows 7 doesn't play well when it's inside Xen which is inside KVM. According to your report, Windows 10 (surprisingly) seems to work under such setup.

For the MD5 sum you've provided, I see that this disk image is at least 5 years old. Could you try again with a more recent image ( https://www.microsoft.com/pl-pl/software-download/windows10 - there is an option to download ISO directly if you visit the page using a browser on Linux)?

Introspection tools are usually adjusted for the latest OS versions. Your particular bug is about LibVMI not being able to find Windows kernel in the memory. I suppose it may be so old and different that it simply could not detect it at all.

**Comment by LANopop** [comment] 2020-05-06 20:25
downloaded the newest version from the page you mentioned and after 30 minutes of me starring at the windows 10 logo i gave up. I dont think it is working :(

**Comment by icedevml** [comment] 2020-05-06 22:06
@LANopop Unfortunately, nested virtualization is very tricky and we don't officially support the setup with Xen nested inside KVM. This doesn't even have much to do with DRAKVUF Sandbox itself. If the VM is hanging during installation process, this is the problem with Xen, KVM or both.

If you have the possibility to use a dedicated server for it, DRAKVUF Sandbox would be most stable. We are also actively working to prepare a compatibility list, just to find out which popular cloud solutions (like Google Cloud Platform) are compatible with our sandbox and this would be published soon.

**Comment by LANopop** [comment] 2020-05-07 09:51
here is the windows 7 bluescreen if anyone is interested

![image](https://user-images.githubusercontent.com/2630216/81280635-10689580-9059-11ea-9a41-42615d027b67.png)

**Comment by icedevml** [comment] 2020-05-07 16:36
Closing this for now, as nested virtualization is unfortunately not well supported due to Xen/KVM issues.

**Closed by icedevml** 2020-05-07 16:36 UTC
Labels: bug
