### ISSUE TITLE
DrakRun - Failed to process task -  'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by Bondey** [CERT-Polska/drakvuf-sandbox#216] opened 2020-08-20 13:34 UTC
Just installed following Readme.md steps and worked very well on Ubuntu 20.04 

I created de VM and made the PostInstallation .

I tested the sandbox without network using pafish.exe (https://github.com/a0rtega/pafish.git) and got a correct report
but after installing ProcDOT I can't get reports of any new analysis.

I keep getting this error on "journalctl -e -u drakrun@1":

`Traceback (most recent call last):`
`  File "/opt/venvs/drakrun/lib/python3.8/site-packages/karton2/karton.py", line 173, in internal_process`
`    self.process()`
`  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/main.py", line 460, in process`
`    self.generate_graphs(outdir)`
`  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/main.py", line 203, in generate_graphs`
`    for csv_line in parse_logs(f):`
`  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/drakparse.py", line 177, in parse_logs`
`    converted = str(plugin_obj(line_obj))`
`  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/drakparse.py", line 59, in __init__`
`    detail = f"Type: REG_BINARY, Length: {len(obj['Value'].replace(' ', ''))}, Data: {obj['Value']}"`
`AttributeError: 'NoneType' object has no attribute 'replace'`

**Comment by Bondey** [comment] 2020-08-24 10:19
It work's! :)

thank you

**Comment by Latanyor** [comment] 2020-09-24 08:33
I had the same issue and the provisional fix did help, either way, my reports are not generated properly because of some figures in the `drakmon.log`:

```
{"Plugin":"apimon","TimeStamp":"1600675570.464648","PID":1584,"PPID":3508,"TID":2304,"UserName":"SessionID","UserId":1,"ProcessName":"\\Device\\HarddiskVolume2\\Users\\peter\\Desktop\\resumee.exe","Method":"LdrGetDllHandle","Event":"api_called","ProcessName":"\\Device\\HarddiskVolume2\\Users\\peter\\Desktop\\resumee.exe","Method":"LdrGetDllHandle","CalledFrom":1992691118,"ReturnValue":0,"Arguments":["0x1","0x0","0x18edb0:\"덀b鮥盀\"","0x18ed78"]}
```

There are several similar figs in the whole log:
![more_chinese_figs_in_log](https://user-images.githubusercontent.com/35563666/94121110-3ef0dc80-fe51-11ea-86fb-a1fbf74fd8ab.jpg)


The parsing stops at the figs and the wohle line is not parsed till the end:

```
Sep 21 10:16:40 milano drakrun[1105]: [2020-09-21 10:16:40,302][ERROR] BUG: Failed to parse drakmon.log line: {"Plugin":"apimon","TimeStamp":"1600676121.857509","PID":3732,"PPID":1584,"TID":3260,"UserName":"SessionID","UserId":1,"Process":"apimon","TimeStamp":"1600676121.857509","PID":3732,"PPID":1584,"TID":3260,"UserName":"SessionID","UserId":1,"ProcessName":"\\Device\\HarddiskVolume2\\Users\\peter\\AppData\\Local\\DevicePairingFolder\\odbc32gt.exe","Method":"LdrGetDllsName":"\\Device\\HarddiskVolume2\\Users\\peter\\AppData\\Local\\DevicePairingFolder\\odbc32gt.exe","Method":"LdrGetDllHandle","Event":"api_called","ProcessName":"\\Device\\HarddiskVolume2\\Users\\peter\\AppData\\Local\\DevicePairingFoldlHandle","Event":"api_called","ProcessName":"\\Device\\HarddiskVolume2\\Users\\peter\\AppData\\Local\\DevicePairingFolder\\odbc32gt.exe","Method":"LdrGetDllHandle","CalledFrom":1992691118,"ReturnValue":0,"Arguments":["0x1","0x0","0x18e17der\\odbc32gt.exe","Method":"LdrGetDllHandle","CalledFrom":1992691118,"ReturnValue":0,"Arguments":["0x1","0x0","0x18e17c:\"乀Ɍ鮥盀
```

**Comment by icedevml** [comment] 2020-09-24 09:26
@Latanyor We will fix this upstream in DRAKVUF. Thanks for reporting.

**Comment by BonusPlay** [comment] 2020-09-24 10:19
This might be connected to #230 where certain symbols break logging.

**Comment by BonusPlay** [comment] 2020-09-28 11:03
Might be also connected to #178

**Comment by icedevml** [comment] 2020-09-28 13:55
I think we neeed to open log files in binary mode, scan for `b"\n"` and then decode/json parse each line independently to guarantee robustness. Of course we need to make fixes in DRAKVUF as well.

**Comment by icedevml** [comment] 2020-09-28 20:00
closing as the fix originally described in this issue is confirmed to be working;

**Closed by icedevml** 2020-09-28 20:00 UTC
Labels: bug
