### ISSUE TITLE
ProcDOT integration doesn't work

### ISSUE THREAD

**Issue by yuriufo** [CERT-Polska/drakvuf-sandbox#380] opened 2020-12-10 01:54 UTC
**Describe the bug**

After upgrading from `v0.10.2` to` v0.13.0`, I ran the analysis again and found that "ProcDOT integration" doesn't work.

![image](https://user-images.githubusercontent.com/30290025/101710841-411c1c00-3acd-11eb-9653-c145d430541e.png)

But `ProcDOT` is indeed installed on my OS.

![image](https://user-images.githubusercontent.com/30290025/101710959-86404e00-3acd-11eb-89f5-6ba53aebf1be.png)

**Comment by BonusPlay** [comment] 2020-12-10 16:28
This is a duplicate of #378.

**Closed by BonusPlay** 2020-12-10 16:28 UTC
Labels: bug
